import { ServiceItem } from '../types';
import { Language } from './translations';

const SERVICES_DATA_ES: ServiceItem[] = [
  {
    id: 'paneles-solares',
    name: 'Paneles Solares',
    shortName: 'Fotovoltaica',
    headline: 'Sistemas Fotovoltaicos de Alta Eficiencia y Autoconsumo',
    tagline: 'Generación distribuida para reducir hasta un 95% de la factura eléctrica con retorno garantizado.',
    description: 'Diseño, suministro, instalación y gestión de interconexión oficial CFE de sistemas solares fotovoltaicos sobre cubiertas industriales, comerciales y residenciales. Utilizamos módulos solares monocristalinos Tier-1 con tecnología TOPCon y microinversores de máxima disipación térmica.',
    accentColor: '#D4AF37',
    glowColor: 'rgba(212, 175, 55, 0.3)',
    icon: 'SunMedium',
    imagePath: '/src/assets/images/hero_solar_infrastructure_1791054682087.jpg',
    metrics: [
      { label: 'Ahorro Eléctrico', value: 'Hasta 95%', detail: 'Sobre tarifas GDMTH y DAC' },
      { label: 'Retorno Inversión', value: '2.8 a 3.6', detail: 'Años periodo promedio' },
      { label: 'Garantía Módulos', value: '25 Años', detail: 'Rendimiento lineal al 85%' },
      { label: 'Interconexión CFE', value: '100% Legal', detail: 'Gestión y medidor bidireccional' },
    ],
    technicalSpecs: [
      { label: 'Tecnología de Célula', value: 'Monocristalino N-Type TOPCon / Bifacial' },
      { label: 'Eficiencia de Módulo', value: '22.8% a 23.4%' },
      { label: 'Inversores Certificados', value: 'SMA / Fronius / Enphase / Huawei FusionSolar' },
      { label: 'Estructura Portante', value: 'Aluminio anodizado AL6005-T5 antiviento 180 km/h' },
      { label: 'Protecciones DC/AC', value: 'Supresores de sobretensión Clase II + Seccionador bajo carga' },
      { label: 'Monitoreo', value: 'Telemetría IoT en tiempo real vía App móvil y Web' },
    ],
    standards: [
      'NOM-001-SEDE-2012',
      'IEC 61215 / IEC 61730',
      'UL 1703 / UL 1741',
      'Manual CFE G0100-04',
    ],
    mockupPresetId: 'solar',
    subOffers: [
      {
        id: 'paneles-industrial',
        name: 'Sistemas Industriales & Naves',
        description: 'Instalaciones sobre techumbres de lámina KR-18, panel sandwich o losas de concreto con fijación no invasiva.',
        specs: ['Capacidades desde 50 kWp hasta 500 kWp', 'Optimizadores de sombra integrados', 'Cálculo estructural de cargas vivas y muertas'],
        recommendedFor: 'Plantas de manufactura, cedis y parques logísticos',
      },
      {
        id: 'paneles-comercial',
        name: 'Comercial & Negocios Medianos',
        description: 'Soluciones llave en mano para plazas comerciales, oficinas corporativas, gasolineras y hospitales.',
        specs: ['Tarifa GDMTH / GDMTO', 'Monitoreo de factor de potencia', 'Cero inyección configurable a red'],
        recommendedFor: 'Supermercados, clínicas, cadenas de retail y colegios',
      },
      {
        id: 'paneles-residencial',
        name: 'Residencial Alto Consumo (DAC)',
        description: 'Sistemas estéticos de bajo perfil con microinversores individuales para eliminar tarifas de alto costo.',
        specs: ['Arquitectura modular ampliable', 'Seguridad por módulo <60V DC', 'App de telemetría familiar'],
        recommendedFor: 'Residencias en tarifa DAC y desarrollos premium',
      },
      {
        id: 'paneles-aislados',
        name: 'Sistemas Híbridos y Off-Grid',
        description: 'Generación solar combinada con almacenamiento en baterías de litio LiFePO4 para zonas sin red o respaldo crítico.',
        specs: ['Inversor híbrido senoidal pura', 'Tiempo de transferencia UPS <10ms', 'Bancos modulares de almacenamiento'],
        recommendedFor: 'Ranchos, telecomunicaciones remotas y bombeo solar',
      },
    ],
  },
  {
    id: 'pavimentacion',
    name: 'Pavimentación & RoadBuilder®',
    shortName: 'Vial & RoadBuilder',
    headline: 'Tecnología Ecológica RoadBuilder® y Pavimentación de Alta Durabilidad',
    tagline: 'Estabilización de suelos no petrolera, control de polvo, imprimación ecológica y preservación vial con TSW, TSB, SX Prime y SX Fog.',
    description: 'Suministro y aplicación oficial de soluciones ecológicas para infraestructura vial RoadBuilder® (SX Systems - roadbuilderproducts.com), desarrolladas con tecnología de la Universidad de Texas en Austin. Reemplazamos los cortes petroleros tradicionales y solventes contaminantes mediante: estabilización polimérica de suelos TSW, recubrimiento de rodadura tipo asfalto en frío TSB, imprimación ecológica SX Prime (reemplazo superior de MC-30) y rejuvenecimiento de pavimentos con SX Fog.',
    accentColor: '#0B2545',
    glowColor: 'rgba(11, 37, 69, 0.4)',
    icon: 'Layers',
    imagePath: '/src/assets/images/service_road_paving_1791054693036.jpg',
    metrics: [
      { label: 'Suelos Estabilizados', value: '+450,000 m²', detail: 'Con polímeros ecológicos TSW/TSB' },
      { label: 'Cero Emisiones VOC', value: '100% Ecológico', detail: 'Tecnología no petrolera UT Austin' },
      { label: 'Sustituto de MC-30', value: 'SX Prime (TP)', detail: 'Imprimación de penetración profunda' },
      { label: 'Preservación Asfáltica', value: 'SX Fog (TF)', detail: 'Sellado de microfisuras y rejuvenecimiento' },
    ],
    technicalSpecs: [
      { label: 'Química Polimérica', value: 'Emulsión polimérica líquida no petrolera en base agua (cero VOCs)' },
      { label: 'Estabilización TSW', value: 'Cohesiona y cementa partículas de suelo; sustituye cal y cemento' },
      { label: 'Superficie TSB', value: 'Capa de rodadura negra en frío (~0.5 L/m²) sin calderas ni riesgo de quemaduras' },
      { label: 'Imprimación SX Prime', value: 'Sustituto de MC-30 con penetración en bases granulares >15mm' },
      { label: 'Preservación SX Fog', value: 'Fog seal (~0.45 L/m²) para sellado de microfisuras y freno de oxidación' },
      { label: 'Apertura al Tráfico', value: 'Express en pocas horas post-aplicación' },
    ],
    standards: [
      'Tecnología desarrollada en University of Texas at Austin',
      'Cumplimiento de normas SCT y ASTM para estabilización de suelos',
      'Protocolos AASHTO de diseño de pavimentos ecológicos',
      'Certificación ISO 9001:2015 en Aseguramiento de Calidad',
    ],
    mockupPresetId: 'paving',
    subOffers: [
      {
        id: 'roadbuilder-tsw',
        name: 'Top-Seal White (TSW) - Estabilización & Control de Polvo',
        description: 'Estabilizador de suelos líquido no petrolero que transforma suelos sueltos y subrasantes en matrices sólidas, impermeables y flexibles.',
        specs: ['Se mezcla con agua y aplica con equipo convencional', 'Incrementa drásticamente la capacidad de soporte (CBR)', 'Elimina emisiones de polvo y costos de mantenimiento'],
        recommendedFor: 'Caminos rurales, plataformas industriales/mineras, helipuertos, estacionamientos y taludes',
      },
      {
        id: 'roadbuilder-tsb',
        name: 'Top-Seal Black (TSB) - Superficie de Rodadura en Frío',
        description: 'Recubrimiento polimérico negro que crea una superficie de rodadura continua tipo asfalto sin usar productos petroleros ni calentamiento.',
        specs: ['Aplicación en frío a ~0.5 L/m² sin riesgo térmico', 'Sella la base contra infiltraciones de agua y aire', 'Mejora fricción superficial y acorta distancias de frenado'],
        recommendedFor: 'Caminos rurales, vialidades de parques industriales, reciclado en frío (CIR) y accesos',
      },
      {
        id: 'roadbuilder-sx-prime',
        name: 'SX Prime (TP) - Imprimación No Petrolera (Reemplazo MC-30)',
        description: 'Imprimación líquida ecológica formulada para reemplazar el asfalto cortado MC-30 con alta penetración, excelente adherencia y sin VOCs.',
        specs: ['Penetración profunda en bases granulares', 'Reduce material desprendido durante la construcción', 'Tiempos de espera mucho más cortos para la capa de rodadura'],
        recommendedFor: 'Bases estabilizadas, carreteras secundarias, estacionamientos y vialidades internas',
      },
      {
        id: 'roadbuilder-sx-fog',
        name: 'SX Fog (TF) - Preservación & Rejuvenecimiento de Pavimentos',
        description: 'Tratamiento tipo fog seal que sella microfisuras, frena la oxidación del asfalto y devuelve el color negro renovado a bajo costo.',
        specs: ['Dosificación ligera (~0.45 L/m²)', 'Prolonga la vida útil del pavimento retrasando obras mayores', 'Impide la entrada de agua y aire que degradan la estructura'],
        recommendedFor: 'Carreteras envejecidas, sellos de gravilla con desgaste, pistas y calles de rodaje',
      },
    ],
  },
  {
    id: 'almacenamiento-bess',
    name: 'Almacenamiento BESS',
    shortName: 'Baterías BESS',
    headline: 'Sistemas de Almacenamiento de Energía en Baterías (BESS) de Grado Industrial',
    tagline: 'Peak shaving, arbitraje de energía, respaldo ininterrumpido y cumplimiento del Código de Red 2.0.',
    description: 'Soluciones integrales de almacenamiento de energía mediante baterías (BESS - Battery Energy Storage Systems) para usuarios industriales y comerciales conectados en Media y Alta Tensión (tarifas GDMTH, DIST y DIT). Optimizamos el perfil de consumo reduciendo la demanda máxima facturable (Peak Shaving), mitigando interrupciones eléctricas críticas y permitiendo el arbitraje tarifario con tecnología de celdas de Litio Ferro-Fosfato (LiFePO4).',
    accentColor: '#E5A823',
    glowColor: 'rgba(229, 168, 35, 0.35)',
    icon: 'BatteryCharging',
    imagePath: '/src/assets/images/service_bess_storage_1791055570883.jpg',
    metrics: [
      { label: 'Reducción de Demanda', value: 'Hasta 40%', detail: 'Recorte de picos en horas punta' },
      { label: 'Tiempo de Transferencia', value: '< 20 ms', detail: 'Conmutación UPS sin caída' },
      { label: 'Vida Útil Celdas', value: '+6,000 Ciclos', detail: '80% DoD con celdas LiFePO4' },
      { label: 'Eficiencia Round-Trip', value: '> 88%', detail: 'Rendimiento AC-AC del sistema' },
    ],
    technicalSpecs: [
      { label: 'Química de Batería', value: 'Litio Ferro-Fosfato (LiFePO4) grado automotriz y utility' },
      { label: 'Capacidades Modulares', value: 'Desde 100 kWh hasta sistemas contenerizados de 5+ MWh (20ft / 40ft ISO)' },
      { label: 'Sistema de Gestión (BMS)', value: 'BMS de 3 niveles con monitoreo celda por celda' },
      { label: 'Software EMS Inteligente', value: 'Despacho predictivo de carga/descarga con Machine Learning' },
      { label: 'Seguridad contra Incendios', value: 'Supresión aerosolizada / Novec 1230 y detección según NFPA 855' },
      { label: 'Climatización de Precisión', value: 'HVAC redundante / refrigeración líquida control ±2°C' },
    ],
    standards: [
      'Código de Red 2.0 (CRE México)',
      'NFPA 855 (Instalación de Sistemas de Almacenamiento)',
      'UL 9540 / UL 9540A (Seguridad desbordamiento térmico)',
      'UL 1973 e IEC 62619 para celdas industriales',
    ],
    mockupPresetId: 'solar',
    subOffers: [
      {
        id: 'bess-peak-shaving',
        name: 'Peak Shaving (Reducción de Demanda Punta)',
        description: 'Descarga automatizada de baterías durante los periodos de máxima demanda y horas punta de CFE para recortar drásticamente los cargos por potencia.',
        specs: ['Atenuación de cargos por kW en tarifa GDMTH', 'Programación horaria automática vía EMS', 'Amortización de inversión de 3 a 4 años'],
        recommendedFor: 'Plantas de manufactura, fundidoras, inyectoras de plástico y centros comerciales',
      },
      {
        id: 'bess-arbitraje',
        name: 'Arbitraje de Energía (Energy Arbitrage)',
        description: 'Carga del sistema BESS en horarios base donde la energía tiene el costo más bajo de la red o con excedente solar, y descarga en horas punta.',
        specs: ['Aprovechamiento del diferencial de costo por kWh', 'Integración simbiótica con paneles solares', 'Cero desperdicio de generación limpia'],
        recommendedFor: 'Industrias con operación continua 24/7 y contratos de suministro calificado',
      },
      {
        id: 'bess-respaldo-critico',
        name: 'Respaldo Ininterrumpido & Microredes Autónomas',
        description: 'Protección integral ante apagones, caídas de tensión y fluctuaciones de CFE, actuando como un sistema UPS industrial de gran escala.',
        specs: ['Tiempo de respuesta ultra-rápido (<20 ms)', 'Transición fluida a modo isla (Islanding)', 'Soporte para cargas dinámicas y arranque de motores'],
        recommendedFor: 'Hospitales, data centers, cámaras farmacéuticas y plantas de proceso continuo',
      },
      {
        id: 'bess-calidad-energia',
        name: 'Calidad de Energía & Soporte Código de Red 2.0',
        description: 'Aporte instantáneo de potencia reactiva, corrección de factor de potencia y regulación de frecuencia para cumplir la normativa de la CRE.',
        specs: ['Regulación de voltaje en punto de conexión', 'Filtrado activo de distorsión armónica', 'Monitoreo continuo conforme a requerimientos CENACE'],
        recommendedFor: 'Centros de carga en Media y Alta Tensión con requerimientos de la CRE',
      },
    ],
  },
  {
    id: 'iluminacion-led',
    name: 'Iluminación LED',
    shortName: 'Smart LED',
    headline: 'Iluminación LED Inteligente para Vialidades, Municipios e Industria',
    tagline: 'Alumbrado público con telegestión IoT y luminarias industriales de alta disipación térmica.',
    description: 'Transformación luminotécnica de vialidades, avenidas, centros urbanos e instalaciones industriales con luminarias LED de grado vial e industrial. Implementamos sistemas de telegestión remota mediante protocolos inalámbricos LoRaWAN / NB-IoT que permiten regular intensidades, detectar fallas en tiempo real y optimizar el consumo hasta en un 70%.',
    accentColor: '#10B981',
    glowColor: 'rgba(16, 185, 129, 0.35)',
    icon: 'Lightbulb',
    imagePath: '/src/assets/images/service_smart_lighting_1791054704684.jpg',
    metrics: [
      { label: 'Luminarias Activas', value: '+35,000', detail: 'Puntos de luz instalados' },
      { label: 'Ahorro Energético', value: '68% a 74%', detail: 'Vs vapor de sodio tradicional' },
      { label: 'Vida Útil LED', value: '100,000 hrs', detail: 'L70B10 certificada' },
      { label: 'Respuesta Telegestión', value: '< 2 seg', detail: 'Comando de atenuación remota' },
    ],
    technicalSpecs: [
      { label: 'Eficacia Luminosa', value: '160 a 185 lúmenes/Watt certificados' },
      { label: 'Chip LED & Driver', value: 'Lumileds / Cree LED con driver MeanWell programable' },
      { label: 'Grado de Protección', value: 'IP66 estanco al agua / IK09 resistencia al impacto' },
      { label: 'Protección contra Picos', value: 'Supresor de 10 kV / 10 kA integrado de serie' },
      { label: 'Conectividad IoT', value: 'Nodo Zhaga / NEMA 7 pines con LoRaWAN / Celular' },
      { label: 'Temperatura de Color', value: '3000K (Cálido Amigable Fauna) a 5000K' },
    ],
    standards: [
      'NOM-031-ENER-2019 (Alumbrado público)',
      'NOM-013-ENER-2013 (Sistemas de alumbrado vial)',
      'Certificación IES LM-79 y LM-80',
      'Protocolo Zhaga Book 18',
    ],
    mockupPresetId: 'lighting',
    subOffers: [
      {
        id: 'led-publico',
        name: 'Alumbrado Público Smart City',
        description: 'Luminarias de brazo vial con curvas fotométricas Tipo II y III para calles, avenidas y periféricos.',
        specs: ['Atenuación programable horaria', 'Conector NEMA 7-pins', 'Cuerpo de fundición de aluminio ADC12'],
        recommendedFor: 'Municipios, gobiernos estatales y desarrollos urbanos',
      },
      {
        id: 'led-industrial',
        name: 'High-Bay Industrial & Campanas',
        description: 'Luminarias para techos altos (8m a 16m) en naves industriales, almacenes con racks y hangares.',
        specs: ['Ópticas focalizadas 60°/90°', 'Resistencia a temperaturas hasta 55°C', 'Regulación 0-10V y DALI-2'],
        recommendedFor: 'Centros de distribución, fundidoras y maquiladoras',
      },
      {
        id: 'led-solar-autonoma',
        name: 'Luminarias Solares Todo-en-Uno',
        description: 'Postes autónomos con panel solar monocristalino, batería LiFePO4 y sensor de movimiento de microondas.',
        specs: ['Autonomía de 3 a 5 días nublados', 'Cero cableado ni canalización subterránea', 'Encendido crepuscular automático'],
        recommendedFor: 'Caminos rurales, fraccionamientos campestres y perímetros de seguridad',
      },
      {
        id: 'led-telegestion',
        name: 'Plataforma Centralizada de Telegestión',
        description: 'Software cloud para encendido, apagado, regulación y monitoreo individual de cada punto de luz desde mapa GIS.',
        specs: ['Mapa interactivo de activos luminotécnicos', 'Alertas de falla inmediata vía SMS/Email', 'Medición de consumo eléctrico real'],
        recommendedFor: 'Direcciones de Servicios Públicos y administradores de parques industriales',
      },
    ],
  },
  {
    id: 'inteligencia-artificial',
    name: 'Inteligencia Artificial',
    shortName: 'IA & Prototipos',
    headline: 'IA Aplicada a Negocios Digitales, Telemetría e Infraestructura Inteligente',
    tagline: 'Desarrollo de prototipos de negocios digitales, gemelos digitales y visión por computadora para toma de decisiones.',
    description: 'Ingeniería de software de vanguardia e Inteligencia Artificial para digitalizar e interconectar negocios. Creamos prototipos digitales funcionales, gemelos virtuales de plantas energéticas, algoritmos de visión artificial para inspección milimétrica de pavimentos y modelos predictivos para optimizar operaciones en tiempo real.',
    accentColor: '#38BDF8',
    glowColor: 'rgba(56, 189, 248, 0.35)',
    icon: 'Cpu',
    imagePath: '/src/assets/images/service_ai_telemetry_1791054719457.jpg',
    metrics: [
      { label: 'Precisión Algorítmica', value: '98.7%', detail: 'Detección de fallas y anomalías' },
      { label: 'Tiempo de Inferencia', value: '< 45 ms', detail: 'Procesamiento Edge de visión' },
      { label: 'Ahorro Operativo', value: '-32%', detail: 'En costos de mantenimiento predictivo' },
      { label: 'Velocidad Prototipado', value: '10x', detail: 'MVP listos para validación de mercado' },
    ],
    technicalSpecs: [
      { label: 'Modelos de Visión', value: 'YOLOv10 y Segment Anything para fisuras y termografía' },
      { label: 'Time-Series IA', value: 'Pronóstico de generación fotovoltaica con datos GFS/NOAA' },
      { label: 'Arquitectura Cloud', value: 'Microservicios desacoplados Kubernetes con API REST / GraphQL' },
      { label: 'Seguridad de Datos', value: 'Alineación ISO/IEC 27034 (SSD) y cifrado AES-256' },
      { label: 'Integración IoT', value: 'Brokers MQTT con latencia sub-segundo para telemetría' },
      { label: 'Plataformas UI/UX', value: 'Apps móviles React Native / Flutter y dashboards Web 4K' },
    ],
    standards: [
      'ISO/IEC 27034 (Seguridad por Diseño)',
      'ISO/IEC 42001 (Sistemas de Gestión de IA)',
      'NIST Cybersecurity Framework',
      'OWASP ASVS Level 2',
    ],
    mockupPresetId: 'ai',
    subOffers: [
      {
        id: 'ai-prototipos-digitales',
        name: 'Prototipado de Negocios Digitales (UI/UX)',
        description: 'Diseño y simulación de interfaces móviles y web interactivas para validar modelos de negocio antes de programar.',
        specs: ['Flujos de usuario U-First interactivos', 'Design System escalable', 'Pruebas de usabilidad cuantitativas'],
        recommendedFor: 'Startups, corporativos en transformación digital y nuevas líneas de negocio',
      },
      {
        id: 'ai-vision-infraestructura',
        name: 'Visión Artificial para Pavimentos e Inspección',
        description: 'Análisis automatizado con drones y cámaras de alta resolución para detectar baches, agrietamientos y desprendimientos.',
        specs: ['Clasificación automática PCI', 'Geolocalización GPS de defectos', 'Reporte exportable GIS'],
        recommendedFor: 'Concesionarias de autopistas, aeropuertos y contratistas viales',
      },
      {
        id: 'ai-gemelo-digital',
        name: 'Gemelos Digitales (Digital Twin)',
        description: 'Réplica virtual 3D interactiva de plantas solares y sistemas de alumbrado con telemetría en tiempo real.',
        specs: ['Simulación física de degradación', 'Predicción de fallas con 72 hrs de anticipación', 'Dashboards ejecutivos interactivos'],
        recommendedFor: 'Operadores de plantas renovables y gerentes de mantenimiento industrial',
      },
      {
        id: 'ai-automatizacion-procesos',
        name: 'Agentes Inteligentes y Automatización',
        description: 'Flujos automatizados con modelos de lenguaje y agentes de software para cotización instantánea y soporte técnico 24/7.',
        specs: ['RAG con bases documentales técnicas de la empresa', 'APIs seguras sin filtración de datos', 'Integración con ERP/CRM'],
        recommendedFor: 'Equipos de ventas técnicas, compras y atención a clientes',
      },
    ],
  },
];

const SERVICES_DATA_EN: ServiceItem[] = [
  {
    id: 'paneles-solares',
    name: 'Solar Panels',
    shortName: 'Photovoltaics',
    headline: 'High-Efficiency Photovoltaic Systems & Commercial Self-Consumption',
    tagline: 'Distributed generation engineered to cut electricity bills by up to 95% with guaranteed payback.',
    description: 'Turnkey design, supply, installation, and formal grid interconnection for rooftop solar PV systems on industrial, logistics, commercial, and residential facilities. We deploy Tier-1 N-Type TOPCon monocrystalline modules and high-dissipation microinverters.',
    accentColor: '#D4AF37',
    glowColor: 'rgba(212, 175, 55, 0.3)',
    icon: 'SunMedium',
    imagePath: '/src/assets/images/hero_solar_infrastructure_1791054682087.jpg',
    metrics: [
      { label: 'Electricity Savings', value: 'Up to 95%', detail: 'On commercial & industrial tariffs' },
      { label: 'Payback Timeline', value: '2.8 to 3.6', detail: 'Years average ROI duration' },
      { label: 'Module Warranty', value: '25 Years', detail: '85% linear output guarantee' },
      { label: 'Utility Filing', value: '100% Compliant', detail: 'Bidirectional metering & permit handling' },
    ],
    technicalSpecs: [
      { label: 'Cell Technology', value: 'N-Type Monocrystalline TOPCon / Bifacial' },
      { label: 'Module Efficiency', value: '22.8% to 23.4%' },
      { label: 'Certified Inverters', value: 'SMA / Fronius / Enphase / Huawei FusionSolar' },
      { label: 'Mounting Racks', value: 'Anodized Aluminum AL6005-T5 rated to 180 km/h wind' },
      { label: 'DC/AC Protection', value: 'Type II Surge Arresters + Load-break disconnect switch' },
      { label: 'Telemetry Monitoring', value: 'Real-time IoT cloud monitoring via Mobile & Web App' },
    ],
    standards: [
      'NOM-001-SEDE-2012',
      'IEC 61215 / IEC 61730',
      'UL 1703 / UL 1741',
      'CFE Manual G0100-04',
    ],
    mockupPresetId: 'solar',
    subOffers: [
      {
        id: 'paneles-industrial',
        name: 'Industrial Plants & Warehouses',
        description: 'Mounting on standing-seam metal roofs, sandwich insulated panels, or concrete slabs with non-penetrating clamps.',
        specs: ['Capacities from 50 kWp to 500+ kWp', 'Integrated shade optimizers', 'Structural dead/live load engineering stamps'],
        recommendedFor: 'Manufacturing plants, distribution centers & logistics parks',
      },
      {
        id: 'paneles-comercial',
        name: 'Commercial & Medium Business',
        description: 'Turnkey solutions for shopping plazas, corporate buildings, fuel stations, and healthcare facilities.',
        specs: ['Commercial peak tariff mitigation', 'Power factor tracking', 'Zero-export grid safety configurations'],
        recommendedFor: 'Supermarkets, clinics, retail chains, and universities',
      },
      {
        id: 'paneles-residencial',
        name: 'High-Demand Residential',
        description: 'Low-profile architectural aesthetics with module-level microinverters to eliminate punitive high utility tiers.',
        specs: ['Modular expandable architecture', 'Safe DC voltage <60V per panel', 'Homeowner mobile telemetry app'],
        recommendedFor: 'Executive residences and luxury real estate developments',
      },
      {
        id: 'paneles-aislados',
        name: 'Hybrid & Off-Grid Energy',
        description: 'Solar generation coupled with LiFePO4 battery banks for off-grid operations or mission-critical facility backup.',
        specs: ['Pure sine wave hybrid inverters', 'UPS transfer speed <10ms', 'Modular battery expansion cabinets'],
        recommendedFor: 'Agricultural operations, remote telecom towers, and solar pumping',
      },
    ],
  },
  {
    id: 'pavimentacion',
    name: 'Eco-Paving & RoadBuilder®',
    shortName: 'RoadBuilder® Systems',
    headline: 'Eco-Friendly RoadBuilder® Technology & Sustainable Roadway Infrastructure',
    tagline: 'Non-petroleum polymer soil stabilization, dust control, eco-prime, and pavement preservation with TSW, TSB, SX Prime and SX Fog.',
    description: 'Official certified partner and applicator of RoadBuilder® (SX Systems) eco-friendly road infrastructure solutions (roadbuilderproducts.com), engineered with proven polymer technology from The University of Texas at Austin. We replace traditional petroleum cutbacks and toxic solvent primes with: TSW liquid soil stabilization and dust control, TSB cold-applied asphalt-like wearing course, SX Prime eco-prime coat (superior replacement for MC-30), and SX Fog microcrack pavement rejuvenation.',
    accentColor: '#0B2545',
    glowColor: 'rgba(11, 37, 69, 0.4)',
    icon: 'Layers',
    imagePath: '/src/assets/images/service_road_paving_1791054693036.jpg',
    metrics: [
      { label: 'Stabilized Soils', value: '+450,000 m²', detail: 'With TSW/TSB non-petroleum polymers' },
      { label: 'Zero VOC Emissions', value: '100% Eco-Friendly', detail: 'Non-petroleum UT Austin technology' },
      { label: 'MC-30 Replacement', value: 'SX Prime (TP)', detail: 'High-penetration solvent-free prime' },
      { label: 'Pavement Rejuvenation', value: 'SX Fog (TF)', detail: 'Microcrack sealing & oxidation halt' },
    ],
    technicalSpecs: [
      { label: 'Polymer Chemistry', value: 'Water-based non-petroleum liquid polymer emulsion (zero VOCs)' },
      { label: 'TSW Stabilization', value: 'Bonds and cements soil particles; replaces lime and cement with higher CBR' },
      { label: 'TSB Wearing Surface', value: 'Cold-applied black surface (~0.5 L/m²) without kettles or burn risks' },
      { label: 'SX Prime (TP)', value: 'Non-petroleum prime replacing MC-30 with deep granular base penetration >15mm' },
      { label: 'SX Fog (TF) Seal', value: 'Light fog seal (~0.45 L/m²) sealing microcracks and reversing oxidation' },
      { label: 'Traffic Reopening', value: 'Rapid cure allowing traffic opening within hours post-application' },
    ],
    standards: [
      'Engineered with technology from The University of Texas at Austin',
      'Compliance with ASTM and SCT roadway stabilization standards',
      'AASHTO mechanistic-empirical design protocols for polymer stabilization',
      'ISO 9001:2015 Quality Management System Certification',
    ],
    mockupPresetId: 'paving',
    subOffers: [
      {
        id: 'roadbuilder-tsw',
        name: 'Top-Seal White (TSW) - Soil Stabilization & Dust Control',
        description: 'Liquid non-petroleum soil stabilizer developed at UT Austin that transforms loose soils and subgrades into strong, water-resistant, flexible matrices.',
        specs: ['Mixed with water and applied with standard earthmoving equipment', 'Drastically increases California Bearing Ratio (CBR)', 'Eliminates dust emissions and recurrent grading costs'],
        recommendedFor: 'Rural and access roads, industrial and mining yards, airstrips, helipads, and embankment slope erosion control',
      },
      {
        id: 'roadbuilder-tsb',
        name: 'Top-Seal Black (TSB) - Cold-Applied Wearing Surface',
        description: 'Black polymer wearing course that creates a continuous asphalt-like surface over treated bases without petroleum binders or heating kettles.',
        specs: ['Cold application at ~0.5 L/m² with zero burn hazards', 'Seals base against water infiltration and air intrusion', 'Improves friction coefficient and shortens braking distance'],
        recommendedFor: 'Secondary and rural roads, industrial park roadways, cold in-place recycling (CIR/FDR), and parking lots',
      },
      {
        id: 'roadbuilder-sx-prime',
        name: 'SX Prime (TP) - Non-Petroleum Prime Coat (MC-30 Replacement)',
        description: 'Eco-friendly liquid prime coat formulated to replace hazardous MC-30 cutback asphalt with deep penetration, superior bonding, and zero VOCs.',
        specs: ['Deep penetration into granular sub-bases', 'Prevents aggregate unraveling during construction', 'Dramatically shorter waiting times prior to surface course placement'],
        recommendedFor: 'Stabilized road bases, secondary highways, parking complexes, and commercial internal avenues',
      },
      {
        id: 'roadbuilder-sx-fog',
        name: 'SX Fog (TF) - Pavement Preservation & Rejuvenation',
        description: 'High-performance fog seal treatment that penetrates and seals hairline microcracks, halts asphalt oxidation, and restores a rich black appearance at minimal cost.',
        specs: ['Light application rate (~0.45 L/m² / 0.1 gal/yd²)', 'Postpones costly major milling and structural resurfacing', 'Forms an impermeable barrier against rain and oxygen degradation'],
        recommendedFor: 'Aging highways, weathered chip seals, airport taxiways, and commercial parking areas',
      },
    ],
  },
  {
    id: 'almacenamiento-bess',
    name: 'BESS Energy Storage',
    shortName: 'BESS Batteries',
    headline: 'Industrial-Grade Battery Energy Storage Systems (BESS)',
    tagline: 'Peak shaving, energy arbitrage, seamless UPS backup, and Grid Code 2.0 regulatory compliance.',
    description: 'Turnkey industrial Battery Energy Storage Systems (BESS) for medium and high-voltage commercial facilities. We optimize power consumption curves by eliminating punitive peak-hour demand spikes (Peak Shaving), providing zero-downtime backup during utility blackouts, and enabling dynamic tariff arbitrage with Lithium Iron Phosphate (LiFePO4) chemistry.',
    accentColor: '#E5A823',
    glowColor: 'rgba(229, 168, 35, 0.35)',
    icon: 'BatteryCharging',
    imagePath: '/src/assets/images/service_bess_storage_1791055570883.jpg',
    metrics: [
      { label: 'Peak Demand Clipping', value: 'Up to 40%', detail: 'Drastic reduction of peak kW charges' },
      { label: 'Transfer Switch Time', value: '< 20 ms', detail: 'Instantaneous industrial UPS handover' },
      { label: 'Cell Cycle Lifespan', value: '+6,000 Cycles', detail: '80% DoD with LiFePO4 cells' },
      { label: 'Round-Trip Efficiency', value: '> 88%', detail: 'AC-to-AC total round-trip performance' },
    ],
    technicalSpecs: [
      { label: 'Battery Chemistry', value: 'Automotive & utility-grade Lithium Iron Phosphate (LiFePO4)' },
      { label: 'Modular Sizing', value: 'From 100 kWh to 5+ MWh ISO containerized enclosures (20ft / 40ft)' },
      { label: 'BMS Management', value: '3-tier BMS monitoring cell voltage, current, and temperature' },
      { label: 'Smart EMS Software', value: 'Predictive charge/discharge dispatch powered by Machine Learning' },
      { label: 'Fire Suppression', value: 'Aerosolized suppression / Novec 1230 gas detection per NFPA 855' },
      { label: 'Precision HVAC', value: 'Redundant liquid cooling with dynamic thermal management ±2°C' },
    ],
    standards: [
      'Grid Code 2.0 (CRE Regulatory Framework)',
      'NFPA 855 (Stationary Energy Storage Systems)',
      'UL 9540 / UL 9540A (Thermal Runaway Mitigation)',
      'UL 1973 & IEC 62619 for Industrial Energy Cells',
    ],
    mockupPresetId: 'solar',
    subOffers: [
      {
        id: 'bess-peak-shaving',
        name: 'Peak Shaving (Demand Reduction)',
        description: 'Automated battery discharge during utility peak tariff hours to significantly slash maximum billing power demand charges.',
        specs: ['Mitigation of peak kW capacity penalties', 'Automatic scheduling via EMS controller', 'Projected payback in 3 to 4 years'],
        recommendedFor: 'Manufacturing factories, metal casting, plastic injection, and commercial malls',
      },
      {
        id: 'bess-arbitraje',
        name: 'Time-of-Use Energy Arbitrage',
        description: 'Charge batteries during base hours when electricity costs are lowest or from excess on-site solar, discharging during peak pricing.',
        specs: ['Capitalizing on tariff price differentials', 'Seamless synergy with solar PV arrays', 'Zero waste of clean solar generation'],
        recommendedFor: '24/7 continuous industrial processes and qualified wholesale market consumers',
      },
      {
        id: 'bess-respaldo-critico',
        name: 'Seamless Backup & Island Microgrids',
        description: 'Instantaneous protection against grid outages, voltage sags, and transient spikes, functioning as a utility-scale industrial UPS.',
        specs: ['Ultra-fast transfer response (<20 ms)', 'Seamless islanding mode transition', 'Dynamic inductive motor-starting support'],
        recommendedFor: 'Hospitals, data centers, pharmaceutical cold storage, and continuous process plants',
      },
      {
        id: 'bess-calidad-energia',
        name: 'Power Quality & Grid Code Compliance',
        description: 'Instant reactive power compensation, power factor correction, and frequency stabilization to satisfy regulatory standards without fines.',
        specs: ['Substation point-of-interconnection voltage support', 'Active harmonic distortion filtering', 'Continuous compliance reporting'],
        recommendedFor: 'Medium and high-voltage load centers subject to strict regulatory compliance',
      },
    ],
  },
  {
    id: 'iluminacion-led',
    name: 'Smart LED Lighting',
    shortName: 'Smart LED',
    headline: 'Intelligent Roadway & Industrial LED Lighting Networks',
    tagline: 'Smart City public lighting with wireless IoT telemanagement and high-heat-dissipation industrial luminaires.',
    description: 'Complete lighting modernization for highways, boulevards, city centers, and industrial facilities with roadway-grade LED fixtures. We integrate wireless LoRaWAN / NB-IoT telemanagement nodes allowing scheduled dimming, instant remote fault detection, and energy savings of up to 70%.',
    accentColor: '#10B981',
    glowColor: 'rgba(16, 185, 129, 0.35)',
    icon: 'Lightbulb',
    imagePath: '/src/assets/images/service_smart_lighting_1791054704684.jpg',
    metrics: [
      { label: 'Active Luminaires', value: '+35,000', detail: 'Smart lighting nodes deployed' },
      { label: 'Energy Savings', value: '68% to 74%', detail: 'Vs traditional sodium vapor lamps' },
      { label: 'LED Service Life', value: '100,000 hrs', detail: 'Certified L70B10 standard' },
      { label: 'Telecontrol Response', value: '< 2 sec', detail: 'Real-time remote dimming command' },
    ],
    technicalSpecs: [
      { label: 'Luminous Efficacy', value: '160 to 185 lumens/Watt certified' },
      { label: 'LED Chip & Driver', value: 'Lumileds / Cree LED with programmable MeanWell / Inventronics driver' },
      { label: 'Ingress Protection', value: 'IP66 waterproof enclosure / IK09 high impact resistance' },
      { label: 'Surge Protection', value: '10 kV / 10 kA integrated surge protector as standard' },
      { label: 'IoT Connectivity', value: 'Zhaga Book 18 / 7-pin NEMA socket with LoRaWAN / Cellular' },
      { label: 'Color Temperature', value: '3000K (Dark-Sky Wildlife Friendly) to 5000K (High CRI)' },
    ],
    standards: [
      'NOM-031-ENER-2019 (Public Lighting)',
      'NOM-013-ENER-2013 (Roadway Lighting)',
      'IES LM-79 and LM-80 Testing',
      'Zhaga Book 18 Smart Interface',
    ],
    mockupPresetId: 'lighting',
    subOffers: [
      {
        id: 'led-publico',
        name: 'Smart City Public Street Lighting',
        description: 'Roadway mast-arm fixtures with Type II and Type III photometric light distribution for streets and expressways.',
        specs: ['Astronomical clock dimming', '7-pin NEMA receptacle', 'Die-cast ADC12 aluminum housing'],
        recommendedFor: 'Municipalities, state transportation agencies, and planned communities',
      },
      {
        id: 'led-industrial',
        name: 'High-Bay Industrial Luminaires',
        description: 'Fixtures engineered for high ceilings (8m to 16m) in manufacturing warehouses, logistics bays, and hangars.',
        specs: ['Focused 60°/90° beam optics', 'Ambient temperature tolerance up to 55°C', '0-10V and DALI-2 dimming protocols'],
        recommendedFor: 'Distribution centers, foundries, and assembly plants',
      },
      {
        id: 'led-solar-autonoma',
        name: 'All-in-One Autonomous Solar Poles',
        description: 'Self-powered street poles with monocrystalline solar panel, long-life LiFePO4 battery, and microwave motion sensor.',
        specs: ['3 to 5 days cloudy weather autonomy', 'Zero trenching or underground cabling required', 'Automatic dusk-to-dawn switching'],
        recommendedFor: 'Rural corridors, perimeter security fences, and country clubs',
      },
      {
        id: 'led-telegestion',
        name: 'Centralized Telemanagement Platform',
        description: 'Cloud dashboard for switching, scheduling, dimming, and health monitoring of individual luminaires on an interactive GIS map.',
        specs: ['Interactive GIS asset map', 'Instant outage alerts via SMS/Email', 'Actual metered electrical consumption tracking'],
        recommendedFor: 'Public works departments and industrial park facility managers',
      },
    ],
  },
  {
    id: 'inteligencia-artificial',
    name: 'Artificial Intelligence',
    shortName: 'AI & Digital Twins',
    headline: 'Applied AI for Digital Business Prototypes, Telemetry & Smart Infrastructure',
    tagline: 'Development of digital business prototypes, digital twins, and computer vision for predictive decision-making.',
    description: 'Software engineering and applied Artificial Intelligence to digitize and optimize physical operations. We craft high-fidelity digital prototypes, 3D virtual twins of renewable energy plants, computer vision models for automated pavement degradation scanning, and predictive analytics for real-time asset management.',
    accentColor: '#38BDF8',
    glowColor: 'rgba(56, 189, 248, 0.35)',
    icon: 'Cpu',
    imagePath: '/src/assets/images/service_ai_telemetry_1791054719457.jpg',
    metrics: [
      { label: 'Algorithmic Accuracy', value: '98.7%', detail: 'Automated anomaly and failure detection' },
      { label: 'Inference Latency', value: '< 45 ms', detail: 'Edge vision model real-time processing' },
      { label: 'Operating Cost Reduction', value: '-32%', detail: 'In predictive maintenance interventions' },
      { label: 'Prototyping Velocity', value: '10x', detail: 'Rapid interactive MVPs for business validation' },
    ],
    technicalSpecs: [
      { label: 'Vision Models', value: 'YOLOv10 and Segment Anything for asphalt cracks and PV thermography' },
      { label: 'Time-Series AI', value: 'Solar output forecasting models correlated with satellite GFS/NOAA' },
      { label: 'Cloud Architecture', value: 'Decoupled Kubernetes microservices with REST / GraphQL & WebSockets' },
      { label: 'Data Security', value: 'ISO/IEC 27034 (SSD) alignment with AES-256 encryption in transit and rest' },
      { label: 'IoT Telemetry Bridge', value: 'Sub-second MQTT message brokers handling thousands of concurrent sensors' },
      { label: 'UI/UX Platforms', value: 'React Native / Flutter mobile apps and 4K Web dashboards with atomic components' },
    ],
    standards: [
      'ISO/IEC 27034 (Security by Design)',
      'ISO/IEC 42001 (AI Management Systems)',
      'NIST Cybersecurity Framework',
      'OWASP ASVS Level 2',
    ],
    mockupPresetId: 'ai',
    subOffers: [
      {
        id: 'ai-prototipos-digitales',
        name: 'Digital Business Prototyping (UI/UX)',
        description: 'Design and interactive simulation of mobile and web interfaces to validate business models before writing code.',
        specs: ['Interactive U-First user flows', 'Scalable enterprise Design System', 'Quantitative benchmark usability testing'],
        recommendedFor: 'Startups, corporate digital transformation, and new digital business units',
      },
      {
        id: 'ai-vision-infraestructura',
        name: 'Computer Vision for Road Inspection',
        description: 'Automated video analytics using drone and high-res vehicle cameras to detect potholes, rutting, and structural fatigue.',
        specs: ['Automated PCI (Pavement Condition Index) scoring', 'GPS geocoding of surface defects', 'Exportable GIS spatial reports'],
        recommendedFor: 'Toll highway operators, airport runways, and roadway contractors',
      },
      {
        id: 'ai-gemelo-digital',
        name: 'Renewable & Utility Digital Twins',
        description: 'Interactive 3D virtual twin of solar plants and municipal lighting grids with real-time telemetry streaming.',
        specs: ['Physics-based degradation modeling', '72-hour advance failure prediction', 'Executive telemetry dashboard'],
        recommendedFor: 'Clean energy facility operators and industrial maintenance directors',
      },
      {
        id: 'ai-automatizacion-procesos',
        name: 'Intelligent Software Agents & RAG',
        description: 'Automated workflows utilizing foundation models and autonomous agents for instant technical quoting and 24/7 client support.',
        specs: ['RAG grounded on company technical and engineering documentation', 'Data-leak-proof private API bridges', 'ERP/CRM bidirectional hooks'],
        recommendedFor: 'Technical sales engineering, procurement, and customer operations',
      },
    ],
  },
];

export const getServicesData = (lang: Language): ServiceItem[] => {
  return lang === 'en' ? SERVICES_DATA_EN : SERVICES_DATA_ES;
};

export const SERVICES_DATA: ServiceItem[] = SERVICES_DATA_ES;
